-- Seed initial E-Books from hardcoded data
-- This migration populates the ebooks table with the original E-Books

INSERT INTO ebooks (slug, title, subtitle, description, long_description, price, pages, reading_time, chapters, features, color, emoji, is_bundle, bundle_items, is_active, sort_order) VALUES
('langversion', 'Der komplette Auswanderer-Guide', 'Ausführliche Langversion', 'Alles was du wissen musst, von der Entscheidung bis zum Ankommen.', E'Der ultimative Leitfaden für alle, die ernsthaft über das Auswandern nachdenken.\n\nDieses E-Book begleitet dich durch jeden Schritt des Prozesses: Von der ersten Idee über die Länderauswahl, Visa-Beantragung, Umzugslogistik bis hin zum erfolgreichen Ankommen in deinem neuen Zuhause.\n\nBasierend auf den Erfahrungen von über 100 erfolgreichen Auswanderern und ständig aktualisiert.', 1999, 250, '6-8 Stunden', '["Die Entscheidung treffen", "Das richtige Land finden", "Visa & Aufenthalt", "Finanzen & Steuern", "Job & Karriere", "Wohnung finden", "Umzug organisieren", "Bürokratie meistern", "Ankommen & Integration", "Netzwerk aufbauen"]'::jsonb, '["25 ausführliche Kapitel", "Länderprofile für 20+ Länder", "Druckbare Checklisten", "Steuer- und Visa-Guide"]'::jsonb, 'from-red-500 to-orange-500', '📕', false, null, true, 1),
('kurzversion', 'Quick Start Guide', 'Kurzversion', 'Die 20% der Informationen, die 80% des Erfolgs ausmachen.', E'Für alle, die schnell loslegen wollen. Dieses kompakte E-Book enthält nur das Wesentliche – keine langen Erklärungen, nur klare Handlungsanweisungen.\n\nPerfekt für schnelle Entscheider, die keine Zeit für lange Lektüre haben, aber trotzdem die wichtigsten Fehler vermeiden wollen.', 999, 80, '2-3 Stunden', '["Die 10 kritischen Schritte", "Entscheidungsbäume", "Quick-Reference Tabellen", "Die 5 größten Fehler", "Sofort-Checkliste"]'::jsonb, '["10 kritische Schritte", "Entscheidungsbäume", "Quick-Reference Tabellen", "Die 5 größten Fehler"]'::jsonb, 'from-green-500 to-teal-500', '📗', false, null, true, 2),
('tips-tricks', 'Tips & Tricks', 'Insider-Wissen', 'Erprobte Hacks von erfahrenen Expats. Geld sparen, Bürokratie umgehen.', E'50+ praktische Hacks, die wir in Jahren des Auswanderns gelernt haben.\n\nVon cleveren Geld-Spar-Strategien über Bürokratie-Shortcuts bis hin zu Netzwerk-Tipps – dieses E-Book enthält das Insider-Wissen, das du nirgendwo anders findest.', 1499, 120, '3-4 Stunden', '["20 Geld-Spar-Hacks", "Bürokratie-Shortcuts", "Wohnungssuche-Tricks", "Netzwerk-Strategien", "Verhandlungs-Tips", "Steuer-Optimierung"]'::jsonb, '["50+ praktische Hacks", "Geld-Spar-Strategien", "Bürokratie-Shortcuts", "Netzwerk-Tipps"]'::jsonb, 'from-blue-500 to-indigo-500', '📘', false, null, true, 3),
('dummies', 'Auswandern für Dummies', 'Einsteigerfreundlich', 'Kein Vorwissen nötig. Alles einfach erklärt, Schritt für Schritt.', E'Du weißt gar nicht, wo du anfangen sollst? Dieses E-Book ist für absolute Anfänger geschrieben.\n\nKeine Fachbegriffe, keine komplizierten Erklärungen – nur einfache Sprache und klare Schritt-für-Schritt Anleitungen. Wir nehmen dich an die Hand und zeigen dir den Weg.', 1299, 100, '2-3 Stunden', '["Was bedeutet Auswandern?", "Bin ich bereit?", "Die ersten Schritte", "Häufige Fragen", "Checklisten für Anfänger"]'::jsonb, '["Einfache Sprache", "Schritt-für-Schritt", "Häufige Fragen beantwortet", "Checklisten für Anfänger"]'::jsonb, 'from-yellow-500 to-amber-500', '📙', false, null, true, 4),
('bundle', 'Komplett-Paket', 'Alle 4 E-Books', 'Alle 4 E-Books zum Sonderpreis. Spare über 30%!', E'Das ultimative Paket für alle, die keine Kompromisse machen wollen.\n\nEnthält alle 4 E-Books:\n• Der komplette Auswanderer-Guide (Langversion)\n• Quick Start Guide (Kurzversion)\n• Tips & Tricks\n• Auswandern für Dummies\n\nEinzeln würden diese E-Books 57,96€ kosten – spare mit dem Bundle über 30%!', 3999, 550, '15+ Stunden', '["Alle Kapitel aus 4 E-Books"]'::jsonb, '["Alle 4 E-Books", "550+ Seiten Wissen", "33% günstiger", "Sofortiger Download"]'::jsonb, 'from-purple-500 to-pink-500', '📚', true, '["langversion", "kurzversion", "tips-tricks", "dummies"]'::jsonb, true, 5)
ON CONFLICT (slug) DO NOTHING;

